### ISSUE TITLE
Cant upload logo in ojs 3.1.0.1

### ISSUE THREAD

**Issue by kctadmin** [ajnyga/allowedUploads#1]
In Log its showing (::1 - - [02/Mar/2018:17:49:16 +0530] “GET /OJS/index.php/art/$$$call$$$/tab/settings/website-settings-tab/show-file-upload-form?fileSettingName=pageHeaderLogoImage&fileType=image&_=1519989177335 HTTP/1.1” 200 115 “http://localhost/OJS/index.php/art/admin/contexts?openWizard=1” “Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.168 Safari/537.36”)

**Comment by kctadmin** [comment]
![screenshot 75](https://user-images.githubusercontent.com/37058937/36958131-aed97494-205f-11e8-8149-026e2d091abc.png)

**Comment by ajnyga** [comment]
I do not think this is connected to the plugin. Because the plugin only hooks into `submissionfilesuploadform::validate` which is not used at all when uploading a logo. And also because the error seems to be related to the users roles?

Or can you confirm that the error disappears if you turn off the plugin?

**Comment by ajnyga** [comment]
ah, ok this could be related after all. I will see what would be the best way to limit effect just to submission file uploads. I was fooled by the hook name. It is used in other contexts as well...

**Comment by ajnyga** [comment]
No, just tested this with 3.1.0.1.
Enabled the plugin and allowed doc; docx; pdf;
Went to journals settings and succesfully uploaded a new logo in jpg format
And then tested sending a submission, there the plugin only allowed those three formats 

So I think that your error is connected to something else?

**Comment by kctadmin** [comment]
thank you @ajnyga 
I cleared that error. some plugin problem now its fine

**Comment by ajnyga** [comment]
ok!
