### ISSUE TITLE
Release ready for plugin gallery

### ISSUE THREAD

**Issue by ajnyga** [ajnyga/allowedUploads#3]
Hi @asmecher

Here is a release ready for the plugin gallery:
https://github.com/ajnyga/allowedUploads/releases/tag/v.1.0

**Comment by asmecher** [comment]
Done -- many thanks for the contribution!

**Comment by ajnyga** [comment]
Thanks @asmecher,
Note that there is still the small problem with the delayed error notification which appears on at the third stage of the file upload wizard. But I have a feeling there is not much I can do about that because I have seen similar delays in other parts of OJS as well. If you do not know what I mean, try to upload a file that is not allowed and then go through the upload wizard with an allowed file. The problem does not affect the way the plugin works but it is a bit weird that the errors appear in the end.

**Comment by asmecher** [comment]
@ajnyga, I think that's a flaw in the error handling code for the file upload wizard. Can you try the changes at https://github.com/pkp/pkp-lib/issues/3488 and see if that works for you?

**Comment by ajnyga** [comment]
Hi @asmecher if I apply those changes to 3.1.0.1 code I get:
```
[18-Mar-2018 20:35:11 Europe/Helsinki] PHP Warning:  assert(): Assertion failed in lib/pkp/controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.inc.php on line 73
[18-Mar-2018 20:35:11 Europe/Helsinki] PHP Warning:  in_array() expects parameter 2 to be array, null given in lib/pkp/controllers/wizard/fileUpload/form/SubmissionFilesUploadForm.inc.php on line 178
[18-Mar-2018 20:35:11 Europe/Helsinki] ojs2: Invalid uploader roles!
```
and upload gets stuck. 

This happens only with the file types that are not allowed so the error is triggered by the error handling.

**Comment by ajnyga** [comment]
Hi @asmecher 
Here is the latest release for OJS 3.1.1.2: https://github.com/ajnyga/allowedUploads/releases/tag/v.1.0.0.2

Note that hte problem above is probably still there?

**Comment by asmecher** [comment]
@ajnyga, sorry for the delay. Just to clarify, what versions of OJS and OMP are this release compatible with? The last release was compatible with...

```
                        <compatibility application="ojs2">
                                <version>3.1.0.0</version>
                                <version>3.1.0.1</version>
                                <version>3.1.1.0</version>
                                <version>3.1.1.1</version>
                                <version>3.1.1.2</version>
                        </compatibility>
                        <compatibility application="omp">
                                <version>3.1.0.0</version>
                                <version>3.1.0.1</version>
                                <version>3.1.1.0</version>
                                <version>3.1.1.1</version>
                                <version>3.1.1.2</version>
                                <version>3.1.1.3</version>
                        </compatibility>
```
Thanks!

**Comment by ajnyga** [comment]
Should be the same. The changes just removed one warning and added support for uppercase extension names. And I updated the license to GPL3. So nothing that should affect compatibility I think.

**Comment by asmecher** [comment]
@ajnyga, sorry for the delay -- I see https://github.com/ajnyga/allowedUploads/releases/tag/v.1.0.0.2 is noted as supporting 3.1.1-2 and newer, so I've updated the plugin gallery accordingly. Is that OK, or does that title need moving (and I can move it back to older versions)?

**Comment by ajnyga** [comment]
Hi,

Yes that release should be ok to use. The only change I have made since is moving to GPL3 (trying to remember to do this for all my plugins). But I will add that to the next release. I probably need to update this plugin for 3.2 anyway because of smarty 3
