### ISSUE TITLE
Relicense to GPL v2 or later

### ISSUE THREAD

**Issue by ctgraham** [ajnyga/allowedUploads#4]
@ajnyga, can you re-license your work on this plugin to "GPL v2 or later" rather than just GPL v2?  For compatibility purposes, we are trying to get to GPL v3 for OJS 3.x.

https://pkp.sfu.ca/wiki/index.php?title=Tech_Committee_Meeting_Minutes_21_March_2018#Software_License_Change

**Comment by ajnyga** [comment]
No problem, can you point me to a license text I could add to my plugins?

**Comment by ctgraham** [comment]
GNU.org describes this:

> The Free Software Foundation may publish revised and/or new versions of the General Public License from time to time. Such new versions will be similar in spirit to the present version, but may differ in detail to address new problems or concerns.  Each version is given a distinguishing version number. If the Program specifies a version number of this License which applies to it and "any later version", you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software Foundation. 

With an example of:

> This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

In the University of Pittsburgh development, we implement this as simply as:
"Released under a license of GPL v2 or later"

https://github.com/ulsdevteam/ojs-sushiLite-plugin#author--license

**Comment by ajnyga** [comment]
@ctgraham I guess this would be ok? https://github.com/pkp/ots/blob/master/LICENSE

Github seems to add the license tag to the upper right corner automatically according to the LICENSE file you have in the repository.

**Comment by ctgraham** [comment]
Github will automatically tag the project according to the LICENSE file it finds.

The individual file headers still retain the reference to GPL v2, however:
https://github.com/ajnyga/allowedUploads/blob/4396fb288c3988f26d9b72d0fd01b831ad23ebc1/AllowedUploadsSettingsForm.inc.php#L8

GPL provides the option of licensing software to a specific GPL version, to version _x_ or later, or to any GPL version ever published:
https://github.com/pkp/ots/blob/11a60c92ee51794095c6266780c65a8cd0cb19eb/LICENSE#L570-L577

I'd recommend updating the text in the headers to indicate "GPL v3" or "GPL v2 or later", or just removing the version reference entirely.

**Comment by ajnyga** [comment]
Should be all GPL3 now.
