### ISSUE TITLE
FBV:Element ID not set

### ISSUE THREAD

**Issue by cpockett** [ajnyga/allowedUploads#5]
I get the following error in OJS 3.1.1.2 after enabling the plugin.  Apparently the text item 'allowedExtensions' requires an id attribute. I've fixed this issue in my own version by changing the following line in allowedUploads/templates/settingsForm.tpl.

![image](https://user-images.githubusercontent.com/23039802/43014920-1a841eda-8c0b-11e8-9b7a-d4659554eb55.png)

`{fbvElement type="text" name="allowedExtensions" value=$allowedExtensions label="plugins.generic.allowedUploads.manager.settings.allowedExtensions"}`

To

` {fbvElement id="allowedExtensions" type="text" name="allowedExtensions" value=$allowedExtensions label="plugins.generic.allowedUploads.manager.settings.allowedExtensions"}
`

I hope this is descriptive enough. I've never really posted an issue before.

**Comment by ajnyga** [comment]
Thanks a lot! I have not had the time to test this with the latest version yet, but will do an upgrade during the weekend.

**Comment by ajnyga** [comment]
I did not get this error, but it is probably due to my own error settings. I added the id you suggested anyway and it will be available in the next version.
