### ISSUE TITLE
Improvement: case insensitive file extensions

### ISSUE THREAD

**Issue by cpockett** [ajnyga/allowedUploads#6]
Would you be able to make the file extensions case insensitive? 

For example currently if I allow only 'doc;mp4' and try to upload a {filename}.MP4 the plugin denies it. Is there a good reason why? From my understanding file extensions are usually case insensitive though windows allows for either.

**Comment by ajnyga** [comment]
Great idea and no reason why this was not included originally.

Here is a new version of allowedUploads including both the changes you suggested: https://github.com/ajnyga/allowedUploads/releases/tag/v.1.0.0.2

Let me know if you have any other problems and thanks for the feedback!

AJ
